apiVersion: skaffold/v2beta9
kind: Config

deploy: 
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: guerrerocristian/client
      context: client #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .
    - image: guerrerocristian/commnets
      context: comments #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .
    - image: guerrerocristian/event-bus
      context: event-bus #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .
    - image: guerrerocristian/moderation
      context: moderation #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .
    - image: guerrerocristian/posts
      context: posts #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .
    - image: guerrerocristian/query
      context: query #directory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # sync any `js` file into the app folder
          - src: '**/*.js'
            dest: .